name: 'Big-bench Hard (CoT)'
type: 'gen'
path: 'bbh_cot/cot'
module: 'tasks.bbh.task.BBHGeneration'
file-pattern:
  test: "**/*.json*"
micro-batch-size: 8
max_gen_length: 400
save-prediction: True
use_task_mask: True