name: 'sports'
type: 'gen'
module: "tasks.cot.task.ChainOfThoughtTask"
path: 'commonsense'
file-pattern:
  test: "sports.json"
sampling_strategy: "BaseStrategy"
prompt_path: "tasks/cot/sports_prompt.txt"
deterministic: true
max_gen_length: 128
use_task_mask: true
save_prediction: true
chain_of_thought: true
micro_batch_size: 4